version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: rt_postgres
    environment:
      POSTGRES_USER: ${PGUSER:-sensor}
      POSTGRES_PASSWORD: ${PGPASSWORD:-sensorpw}
      POSTGRES_DB: ${PGDATABASE:-sensordb}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
volumes:
  pgdata: